project:
  type: website
  output-dir: docs

website:
  title: "warmup-finn-heinemann"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: allArticles.qmd
        text: My Articles


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



