project:
  type: website
  output-dir: docs

website:
  title: "warmup-finn-heinemann"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: article_01.qmd
        text: My own Loop
      - href: article_02.qmd
        text: Table with Sort-Buttons


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



