project:
  type: website
  output-dir: docs

website:
  title: "warmup-finn-heinemann"
  site-path: "/warmup-finn-heinemann/"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: articles/index.qmd
        text: My Articles
      - href: posts/index.qmd
        text: Blog


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



