project:
  type: website
  output-dir: docs

website:
  title: "personal-finn-heinemann"
  site-path: "/personal-finn-heinemann/"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: articles/index.qmd
        text: My Articles
      - href: posts/index.qmd
        text: Blog
  sidebar:
  - id: articles
    logo: images/PaderbornImage.webp
    style: "docked"
    background: light
    collapse-level: 2
    contents:
    - href: index.qmd
      text: Home
    - href: about.qmd
      text: About
    - href: articles/article_01.qmd
      text: My Own Loop
    - href: articles/article_02.qmd
      text: Table-Sort Assignment
    - href: articles/article_03.rmd
      text: Volleyball Visualizations
    - href: posts/index.qmd
      text: Blog


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true




