---
title: "Tigers season ends in 5-set heartbreak"
description: "Blog Post 2"
author:
    - name: Finn Heinemann
date: "2023-11-09"
categories: [Volleyball, NAIA, Georgetown College]
---

The original atricle can be found at this [link](https://georgetowncollege.prestosports.com/sports/mvball/2022-23/releases/20230418k5hkk9)!

Georgetown entered day 2 of pool play in the NAIA Tournament knowing a win must happen to keep hope alive of advancing to the semifinals. The Tigers took on #1 Benedictine-Mesa for the 2nd time this season. The regular season meeting saw the Tigers fall in straight sets. This time, on a neutral floor, Georgetown brought everything it had and then some. Mesa had just a hair more as they took the match in 5 sets, ending Georgetown's season.

In the opener, Mesa raced out to a 5-2 lead before Georgetown answered with 3 of the next 4 to keep close. Thanks to strong early play from Liam Morrissey, the Tigers would take the lead at 10-9. Later in the set, Mesa moved back ahead at 14-13 setting the stage for a Tigers rally that proved to be the difference in the set. Kills from Ryan Gunn and Thomas Dunkley put the Tigers back on top. Kacper Dobrowolski followed with an ace, forcing a Mesa timeout. Another Gunn kill and Dobrowoloski ace put GC up 18-14. Morissey and Miguel Vega would reintroduce themselves to push the lead to 21-15 and the last Mesa timeout. It did little to stem the tide as Tyler Laha put the finishing touches on an impressive 25-19 opening win.

Mesa used the set break to regroup. Out of it, they showed why they earned the top-seed in the tournament. The Redhawks found an offensive rhythm in sets 2 and 3 that very few teams in the country could stop. A .429 2nd set followed by a hitting clip of .577 in the 3rd sent Mesa ahead in the match 2-1, thanks to 25-17 and 25-15 set wins, to push the Tigers to the brink of elimination.

The start of the 4th looked like it would be a mere formality. Mesa scored the first 5 points of the set, forcing the Tigers to call the early timeout. While the Tigers tried to chip away, the Redhawks kept the pressure on and growing the lead to 11-5. Georgetown would finally get some life thanks to Redhawk errors and a Thomas Dunkley ace. It resulted in 4 straight for GC to get the Tigers within 11-9. Mesa would assert itself again to take a 15-10 before Georgetown turned it one of its best runs of the season. With its collective back against the wall, Georgetown went on a stunning 9-1 run to surge to a 19-16 lead. Mesa would stay poised and tie the set at 20, forcing Georgetown to regroup with a timeout. The teams would trade points from there. Leading 22-21, Ryan Gunn found an opening to put the Tigers up 2. He would do it again on the following point to give GC a set point at 24-22. Mesa's final attack went wide and the Tigers pulled off the incredible rally to send the match to a 5th set.

The end of the 4th would prove to be the final high point for Georgetown. As was the case against Saint Xavier, Georgetown fell in a huge hole early against Mesa and couldn't recover. The Redhawks stormed out to an 8-2 lead as the Tigers committed 4 errors in that 10-point stretch. GC did score 3 straight to get within 8-5 but a Mesa kill, followed by another GC attack error, pushed the Mesa lead to 10-5. Georgetown would never get within 4 again as the set and match ended on a Georgetown serve error to bring the 2023 season to a close, as Mesa took the 5th, 15-9.

Ryan Gunn led the Tigers offense with 16 kills but the overall numbers just weren't there in this one. GC hit just .153 for the match, while Mesa hit a .354 clip. One could argue it made the Tiger effort all the more impressive given the offense was not at its best on this day.

Georgetown's season ends with a 21-8 record. The Tigers are slated to return the bulk of the roster in 2024 with the goal and expectation of a deeper run in the tourney.