---
title: "Authentic German Potatoe Salad"
description: "Blog Post 1"
author:
    - name: Finn Heinemann
date: "2023-11-09"
categories: [Cooking, Germany]
---

The original article can be found [here](https://www.allrecipes.com/recipe/83097/authentic-german-potato-salad/)!

This is my mother's recipe for authentic German potato salad. Everyone, German or not, loves it. It is easy to double the recipe as well. I often bring it to potlucks, and we also have it at home on special occasions. There are usually no leftovers, but if there are, they don't last long!

The German potato salad features tender potatoes in a flavorful bacon vinaigrette. 

What Is German Potato Salad?
Unlike mayonnaise-based American potato salads, German potato salad is tossed in a vinegar-based dressing made with bacon drippings. It is usually served warm instead of cold, but some people prefer to serve it at room temperature.

How to Make German Potato Salad
You'll find a detailed ingredient list and step-by-step instructions in the recipe below, but let's go over the basics:

German Potato Salad Ingredients

These are the ingredients you’ll need to make this authentic German potato salad recipe: 

Potatoes: We recommend using waxy potatoes (such as New Potatoes) because they hold their shape well. Yukon Gold, an all-purpose variety, is also a good choice. 
Bacon: Bacon (and its grease) adds tons of meaty flavor to the hearty German potato salad. 
Onion: An onion, cooked in bacon grease, lends even more complexity and flavor. 
Vinegar: White vinegar adds tanginess that cuts through the richness from the potatoes and bacon. 
Sugar: A bit of white sugar gives the savory potato salad subtle sweetness. 
Seasonings and herbs: This German potato salad recipe is seasoned with salt, pepper, and fresh parsley.
Learn more: What Are the Best Potatoes for Potato Salad?

How Do You Make German Potato Salad? 

Here’s a brief overview of what you can expect when you make homemade German potato salad:

Boil, drain, and cool the diced and peeled potatoes. 
Fry the bacon in a skillet, then cook the onion in the bacon grease. 
Add the vinegar, sugar, water, salt, and pepper and bring to a boil. 
Add the potatoes and ½ of the bacon to the boiling liquid. 
When heated through, transfer the potatoes to a serving dish. 
Garnish with remaining bacon and parsley. 
What to Serve With German Potato Salad
This German potato salad would be the perfect addition to any potluck or picnic spread. In need of some more inspiration? Explore our collection of 15 Best Potluck Side Dishes Are So Good Everyone Will Be Begging You for the Recipes. Here are a few of the crowd-pleasing recipes you’ll find: 

Classic Macaroni Salad
Squash Casserole
Perfect Summer Fruit Salad
How Long Does German Potato Salad Last? 
You can store your leftover German potato salad in a shallow, airtight container for up to five days. Reheat in the oven, covered with foil, to prevent the potatoes from drying out. 

Can You Freeze German Potato Salad? 
German potato salads freeze better than their mayonnaise-based counterparts. Freeze the (completely cooled) potato salad for up to three months, then thaw in the fridge and reheat in the oven.  

Allrecipes Community Tips and Praise
“Absolutely delicious,” raves krnanderson2901. “Some German potato salad recipes that I have tried don't have enough tang, but this one has that tangy, bacon flavor I love!”

“I made this tonight and it was outstanding,” according to Tom McCullough Sr. “Didn't have any white wine vinegar so I substituted plain white vinegar and a quarter cup of pinot grigio. Dicing the potatoes before cooking and it cut down on cooking time! This recipe is a keeper!”

“Our family includes picky eaters,” says one Allrecipes community member. “This was an absolute hit with everyone!! The use of the bacon fat to sauté the onions makes this so flavorful!”