---
title: "Paderborn"
description: "Blog Post 3"
author:
    - name: Finn Heinemann
date: "2023-11-09"
categories: [City, Germany]
---

The original article can be found [here](https://en.wikipedia.org/wiki/Paderborn)!

### General

Paderborn (German pronunciation: [paːdɐˈbɔʁn] ⓘ; Westphalian: Patterbuorn, also Paterboärn)[3] is a city in eastern North Rhine-Westphalia, Germany, capital of the Paderborn district. The name of the city derives from the river Pader and Born, an old German term for the source of a river. The river Pader originates in more than 200 springs near Paderborn Cathedral, where St. Liborius is buried.

Paderborn ranks 55th on the List of cities in Germany by population.

### History

Paderborn was founded as a bishopric by Charlemagne in 795, although its official history began in 777 when Charlemagne built a castle near the Paderborn springs.[4] In 799 Pope Leo III fled his enemies in Rome and reached Paderborn, where he met Charlemagne, and stayed there for three months. It was during this time that it was decided that Charlemagne would be crowned emperor. Charlemagne reinstated Leo in Rome in 800 and was crowned as Holy Roman Emperor by Leo in return. In 836, St. Liborius became the patron saint of Paderborn after his bones were moved there from Le Mans by Bishop Badurad.[5] St. Liborius is commemorated in Paderborn every year in July with the Liborifest. The bishop of Paderborn, Meinwerk, became a Prince of the Empire in 1100. The bishop had several large buildings built, and the area became a place for the emperors to stay.The city was taken by Prussia in 1802, then by the French vassal state Kingdom of Westphalia from 1807 to 1813 and then returned to Prussia.

Native Friedrich Sertürner, a pharmacist's apprentice in Paderborn, was the first to isolate morphine from opium in 1804.In 1914 the Paderborn military camp was turned into a prisoner of war camp named Sennelager.

In 1930, the See of Paderborn was promoted to archdiocese.

During World War II, Paderborn was bombed by Allied aircraft in 1944 and 1945, resulting in 85% destruction, including many of the historic buildings. It was seized by the US 3rd Armored Division after a pitched battle 31 March – 1 April 1945, in which tanks and flamethrowers were used during combined mechanized-infantry assaults against the city's southwestern, southern and southeastern approaches.[6]

After the city was reconstructed in the 1940s and 1950s, Paderborn became a major industrial seat in Westphalia.[5] The British Army retained a significant presence in the area until 2020, when British units were relocated back to the United Kingdom. Only a small training and enabling staff remain at Paderborn to facilitate temporary deployments to use the Sennelager Training Area.[7]

On May 20, 2022, Paderborn was hit by a damaging tornado, leaving 38 injured & considerable damage along its path.